### ISSUE TITLE
Create Client API

### ISSUE THREAD

**Issue by iisisrael** [greenhollow/pantry#1]
Client records need an API...

**Comment by iisisrael** [comment]
### Implementation Plan

Since this is the first API implementation, there are some prerequisites:
- [ ] Install the [FOSRestBundle](https://github.com/FriendsOfSymfony/FOSRestBundle)
- [ ] Install the [JMSSerializerBundle](https://jmsyst.com/bundles/JMSSerializerBundle)
- [ ] Install the [NelmilApiDocBundle](https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html)

Then the normal implementation can begin:
- [ ] Create a {{ClientDto}}
- [ ] Create one or more form types for the create / update actions
    * Requirements are a bit fuzzy on this, so we'll have to thunk on it
- [ ] Create a {{ClientApiController}} with four CRUD actions, documenting in the annotations
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
